# Generated by Django 6.0 on 2025-12-10 06:00

import app.models.user
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='ユーザー名', max_length=50, verbose_name='ユーザー名')),
                ('handle', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$')], verbose_name='ハンドルネーム')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('birth_date', models.DateField(validators=[app.models.user.validate_birth_date], verbose_name='生年月日')),
                ('icon', models.ImageField(default='images/default_icon.png', upload_to='uploads', verbose_name='ユーザーアイコン')),
                ('header', models.ImageField(default='images/default_header.jpg', upload_to='uploads', verbose_name='ヘッダー画像')),
                ('bio', models.TextField(blank=True, max_length=160, verbose_name='自己紹介')),
                ('is_private', models.BooleanField(default=False, verbose_name='非公開設定')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The', related_name='app_user_name', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific', related_name='app_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
