# Generated by Django 6.0 on 2025-12-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="app.tweet",
                verbose_name="親ツイート",
            ),
        ),
    ]
